package com.example.samplejavascript.mybatis.domain.mapper;

import com.example.samplejavascript.mybatis.domain.model.Catalogs;
import com.example.samplejavascript.mybatis.domain.model.CatalogsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CatalogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    long countByExample(CatalogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    int deleteByExample(CatalogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    int insert(Catalogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    int insertSelective(Catalogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    List<Catalogs> selectByExample(CatalogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    Catalogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    int updateByExampleSelective(@Param("record") Catalogs record, @Param("example") CatalogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    int updateByExample(@Param("record") Catalogs record, @Param("example") CatalogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    int updateByPrimaryKeySelective(Catalogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalogs
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    int updateByPrimaryKey(Catalogs record);
}