package com.example.samplejavascript.mybatis.domain.model;

import java.util.Date;

public class Catalogs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalogs.id
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalogs.catalog_name
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    private String catalogName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalogs.catalog_name_alias
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    private String catalogNameAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalogs.component_flag
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    private Boolean componentFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalogs.sample_flag
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    private Boolean sampleFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalogs.created_by
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalogs.created_at
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalogs.updated_by
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalogs.updated_at
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalogs.delete_flag
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalogs.id
     *
     * @return the value of catalogs.id
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalogs.id
     *
     * @param id the value for catalogs.id
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalogs.catalog_name
     *
     * @return the value of catalogs.catalog_name
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalogs.catalog_name
     *
     * @param catalogName the value for catalogs.catalog_name
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName == null ? null : catalogName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalogs.catalog_name_alias
     *
     * @return the value of catalogs.catalog_name_alias
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public String getCatalogNameAlias() {
        return catalogNameAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalogs.catalog_name_alias
     *
     * @param catalogNameAlias the value for catalogs.catalog_name_alias
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public void setCatalogNameAlias(String catalogNameAlias) {
        this.catalogNameAlias = catalogNameAlias == null ? null : catalogNameAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalogs.component_flag
     *
     * @return the value of catalogs.component_flag
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public Boolean getComponentFlag() {
        return componentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalogs.component_flag
     *
     * @param componentFlag the value for catalogs.component_flag
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public void setComponentFlag(Boolean componentFlag) {
        this.componentFlag = componentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalogs.sample_flag
     *
     * @return the value of catalogs.sample_flag
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public Boolean getSampleFlag() {
        return sampleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalogs.sample_flag
     *
     * @param sampleFlag the value for catalogs.sample_flag
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public void setSampleFlag(Boolean sampleFlag) {
        this.sampleFlag = sampleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalogs.created_by
     *
     * @return the value of catalogs.created_by
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalogs.created_by
     *
     * @param createdBy the value for catalogs.created_by
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalogs.created_at
     *
     * @return the value of catalogs.created_at
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalogs.created_at
     *
     * @param createdAt the value for catalogs.created_at
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalogs.updated_by
     *
     * @return the value of catalogs.updated_by
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalogs.updated_by
     *
     * @param updatedBy the value for catalogs.updated_by
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalogs.updated_at
     *
     * @return the value of catalogs.updated_at
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalogs.updated_at
     *
     * @param updatedAt the value for catalogs.updated_at
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalogs.delete_flag
     *
     * @return the value of catalogs.delete_flag
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalogs.delete_flag
     *
     * @param deleteFlag the value for catalogs.delete_flag
     *
     * @mbg.generated Wed Jul 31 06:48:50 JST 2019
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}